name: SYSINFO-TEST

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Verifica fisierele din aplicatie
        run: |
          pwd
          ls -la

      - name: Configurare virtual environment. Daca nu exista este creat. Instalare dependinte
        run: |
          . ./activeaza_venv_jenkins
      
      - name: Verificari statice. Verificare calitate cod cu pylint.
        run: |
          #. ./activeaza_venv;
          echo '\n\nVerificare app/lib/*.py cu pylint\n'
          pylint --exit-zero app/lib/*.py

          echo '\n\nVerificare tests/*.py cu pylint'
          pylint --exit-zero app/tests/*.py

          echo '\n\nVerificare sysinfo.py cu pylint'
          pylint --exit-zero sysinfo.py
          
      - name: TESTARE. Unittest cu pytest
        run: |
          #. ./activeaza_venv
          pytest
      
          

